#!/usr/bin/env bash
# Assemble .env.gcp from an existing env file, then report what still needs a
# human decision. Never prints a secret value — only whether one is present.
#
#   ./deploy/make-env.sh .env            # start from your local dev env
#
# Vercel's env vars are write-only (all marked Sensitive), so they cannot be
# exported. Anything missing here has to be re-copied from the provider's own
# dashboard.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="${1:-.env}"
OUT=".env.gcp"
[[ -f "${SRC}" ]] || { echo "no such file: ${SRC}"; exit 1; }

# Mismatching these against production is not merely inconvenient.
declare -a CRITICAL=(CREDENTIAL_ENC_KEYS CREDENTIAL_ENC_ACTIVE BETTER_AUTH_SECRET)
declare -a WANTED=(
  BETTER_AUTH_SECRET GEMINI_API_KEY
  TWILIO_ACCOUNT_SID TWILIO_AUTH_TOKEN TWILIO_SMS_FROM
  STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET
  STRIPE_PRICE_STARTER STRIPE_PRICE_PREMIUM STRIPE_PRICE_PRO
  RESEND_API_KEY EMAIL_FROM
  GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET
  GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET
  FACEBOOK_CLIENT_ID FACEBOOK_CLIENT_SECRET
  CRON_SECRET VOICE_BRIDGE_SECRET
  CREDENTIAL_ENC_KEYS CREDENTIAL_ENC_ACTIVE
  SQUARE_APP_ID SQUARE_APP_SECRET SQUARE_ENVIRONMENT
  SQUARE_WEBHOOK_SIGNATURE_KEY
  TEST_ACCOUNT_EMAILS
)

{
  echo "# Generated by deploy/make-env.sh from ${SRC} on $(date -u +%FT%TZ)"
  echo "# Gitignored via .env*. Delete once pushed to Secret Manager."
  echo
} > "${OUT}"

present=(); missing=()
for k in "${WANTED[@]}"; do
  line="$(grep -E "^${k}=" "${SRC}" | head -1 || true)"
  val="$(printf '%s' "${line}" | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//')"
  if [[ -n "${val}" ]]; then
    printf '%s=%s\n' "${k}" "${val}" >> "${OUT}"; present+=("${k}")
  else
    printf '%s=\n' "${k}" >> "${OUT}"; missing+=("${k}")
  fi
done

chmod 600 "${OUT}"
echo "wrote ${OUT} (chmod 600) — ${#present[@]} carried over, ${#missing[@]} blank"
echo
[[ ${#missing[@]} -gt 0 ]] && { echo "BLANK — fill from the provider's dashboard:"; printf '  %s\n' "${missing[@]}"; echo; }

echo "VERIFY BEFORE PUSHING — a mismatch with production is destructive:"
for k in "${CRITICAL[@]}"; do
  grep -qE "^${k}=.+" "${OUT}" && echo "  ${k}  [carried from ${SRC}]" || echo "  ${k}  [BLANK]"
done
cat <<'TXT'

  CREDENTIAL_ENC_KEYS wraps every tenant's stored POS token. If this value
  differs from the one production is using, those tokens become permanently
  undecryptable and every tenant must reconnect. A dev value is NOT the
  production value unless you deliberately reused it. If you no longer have
  production's, re-key while still on the old host: add a new version, run
  POST /api/admin/integrations/rekey to re-wrap every row, then use that.

  BETTER_AUTH_SECRET signs sessions. A mismatch logs everyone out — annoying
  rather than destructive, but do it knowingly.

  Also confirm STRIPE_SECRET_KEY is the live key if production is live: a dev
  file usually holds sk_test_, and test keys silently see no real customers.
TXT
